// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#pragma once

#include "djinni_support.hpp"
#include "echo_view_model.hpp"

namespace djinni_generated {

class NativeEchoViewModel final : ::djinni::JniInterface<::testsuite::EchoViewModel, NativeEchoViewModel> {
public:
    using CppType = std::shared_ptr<::testsuite::EchoViewModel>;
    using CppOptType = std::shared_ptr<::testsuite::EchoViewModel>;
    using JniType = jobject;

    using Boxed = NativeEchoViewModel;

    ~NativeEchoViewModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeEchoViewModel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeEchoViewModel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeEchoViewModel();
    friend ::djinni::JniClass<NativeEchoViewModel>;
    friend ::djinni::JniInterface<::testsuite::EchoViewModel, NativeEchoViewModel>;

};

}  // namespace djinni_generated
