// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#include "NativeEchoView.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeEchoView::NativeEchoView() : ::djinni::JniInterface<::testsuite::EchoView, NativeEchoView>() {}

NativeEchoView::~NativeEchoView() = default;

NativeEchoView::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeEchoView::JavaProxy::~JavaProxy() = default;

void NativeEchoView::JavaProxy::display_text(const std::string & c_text) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeEchoView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_displayText,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_text)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
