// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#pragma once

#include "djinni_support.hpp"
#include "echo_view.hpp"

namespace djinni_generated {

class NativeEchoView final : ::djinni::JniInterface<::testsuite::EchoView, NativeEchoView> {
public:
    using CppType = std::shared_ptr<::testsuite::EchoView>;
    using CppOptType = std::shared_ptr<::testsuite::EchoView>;
    using JniType = jobject;

    using Boxed = NativeEchoView;

    ~NativeEchoView();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeEchoView>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeEchoView>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeEchoView();
    friend ::djinni::JniClass<NativeEchoView>;
    friend ::djinni::JniInterface<::testsuite::EchoView, NativeEchoView>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::testsuite::EchoView
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void display_text(const std::string & text) override;

    private:
        friend ::djinni::JniInterface<::testsuite::EchoView, ::djinni_generated::NativeEchoView>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/EchoView") };
    const jmethodID method_displayText { ::djinni::jniGetMethodID(clazz.get(), "displayText", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
