// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public interface EchoView {
    public void displayText(@Nonnull String text);

    public static final class WeakProxy implements EchoView
    {
        private final java.lang.ref.WeakReference<EchoView> actual;

        public WeakProxy(EchoView actual)
        {
            this.actual = new java.lang.ref.WeakReference<>(actual);
        }

        @Override
        public void displayText(String text)
        {
            EchoView capturedActual = actual.get();
            if (capturedActual != null)
            {
                capturedActual.displayText(text);
            }
        }
    }
}
