// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

package com.dropbox.djinni.test;

import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public interface EchoViewModel {
    public void didEnterText(@Nonnull String text);

    @CheckForNull
    public static EchoViewModel create(@CheckForNull EchoView view)
    {
        return CppProxy.create(view);
    }

    static final class CppProxy implements EchoViewModel
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void didEnterText(String text)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_didEnterText(this.nativeRef, text);
        }
        private native void native_didEnterText(long _nativeRef, String text);

        @CheckForNull
        public static native EchoViewModel create(@CheckForNull EchoView view);
    }
}
