// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#pragma once

#include <string>

namespace testsuite {

class EchoView {
public:
    virtual ~EchoView() {}

    virtual void display_text(const std::string & text) = 0;
};

}  // namespace testsuite
