// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#import <Foundation/Foundation.h>
@class DBEchoViewModel;
@protocol DBEchoView;


@interface DBEchoViewModel : NSObject

+ (nullable DBEchoViewModel *)create:(nullable id<DBEchoView>)view;

- (void)didEnterText:(nonnull NSString *)text;

@end
