// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#import <Foundation/Foundation.h>


@protocol DBEchoView

- (void)displayText:(nonnull NSString *)text;

@end

@interface DBEchoViewWeakProxy : NSObject<DBEchoView>

@property (weak, nonatomic, nullable) id<DBEchoView> actual;

- (nonnull instancetype) initWithActual:(nonnull id<DBEchoView>)actual;

@end
