// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#import "DBEchoView.h"

@implementation DBEchoViewWeakProxy

- (nonnull instancetype) initWithActual:(nonnull id<DBEchoView>)actual
{
    self = [super init];
    self.actual = actual;
    return self;
}

- (void) displayText:(nonnull NSString *)text
 {
    id<DBEchoView> capturedActual = self.actual;
    if (capturedActual)
    {
        [capturedActual displayText:text];
    }
}

@end
