// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#include "echo_view_model.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBEchoViewModel;

namespace djinni_generated {

class EchoViewModel
{
public:
    using CppType = std::shared_ptr<::testsuite::EchoViewModel>;
    using CppOptType = std::shared_ptr<::testsuite::EchoViewModel>;
    using ObjcType = DBEchoViewModel*;

    using Boxed = EchoViewModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

