// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weak_proxy.djinni

#import "DBEchoViewModel+Private.h"
#import "DBEchoViewModel.h"
#import "DBEchoView+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBEchoViewModel ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::EchoViewModel>&)cppRef;

@end

@implementation DBEchoViewModel {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::EchoViewModel>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::EchoViewModel>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable DBEchoViewModel *)create:(nullable id<DBEchoView>)view {
    try {
        auto objcpp_result_ = ::testsuite::EchoViewModel::create(::djinni_generated::EchoView::toCpp(view));
        return ::djinni_generated::EchoViewModel::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)didEnterText:(nonnull NSString *)text {
    try {
        _cppRefHandle.get()->did_enter_text(::djinni::String::toCpp(text));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto EchoViewModel::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto EchoViewModel::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBEchoViewModel>(cpp);
}

}  // namespace djinni_generated

@end
